[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spotify_to_tidal"
version = "1.0.7"
requires-python = ">= 3.10"

dependencies = [
  "spotipy==2.26.0",
  "tidalapi==0.8.11",
  "pyyaml==6.0.3",
  "tqdm==4.70.0",
  "sqlalchemy==2.0.52",
  "pytest==9.1.1",
  "pytest-mock==3.15.1"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["spotify_to_tidal*"]
namespaces = true

[project.scripts]
spotify_to_tidal = "spotify_to_tidal.__main__:main"
spotify_to_tidal_gui = "spotify_to_tidal.gui:main"
